-- Convert TEXT timestamp columns to TIMESTAMPTZ
ALTER TABLE services
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::TIMESTAMPTZ,
    ALTER COLUMN enabled    TYPE BOOLEAN;

ALTER TABLE check_results
    ALTER COLUMN checked_at TYPE TIMESTAMPTZ USING checked_at::TIMESTAMPTZ;

ALTER TABLE incidents
    ALTER COLUMN started_at  TYPE TIMESTAMPTZ USING started_at::TIMESTAMPTZ,
    ALTER COLUMN resolved_at TYPE TIMESTAMPTZ USING resolved_at::TIMESTAMPTZ;

ALTER TABLE systems
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at::TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at::TIMESTAMPTZ;
